apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-exchange
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
        - image: ezazulhaq02/currency-exchnage-service:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: currency-exchnage-service
          resources:
            limits:
              memory: "128m"
              cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
spec:
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: currency-exchange
  type: LoadBalancer
