apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "1"
      creationTimestamp: "2021-08-25T17:46:03Z"
      generation: 1
      labels:
        app: currency-exchange
      name: currency-exchange
      namespace: default
      resourceVersion: "6290"
      uid: e697957c-3664-49db-92a3-81c85625c045
    spec:
      progressDeadlineSeconds: 600
      replicas: 2
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: currency-exchange
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: currency-exchange
        spec:
          containers:
            - image: ezazulhaq02/currency-exchnage-service:0.0.2-SNAPSHOT
              imagePullPolicy: IfNotPresent
              name: currency-exchnage-service
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
    status:
      availableReplicas: 1
      conditions:
        - lastTransitionTime: "2021-08-25T17:46:23Z"
          lastUpdateTime: "2021-08-25T17:46:23Z"
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: "True"
          type: Available
        - lastTransitionTime: "2021-08-25T17:46:03Z"
          lastUpdateTime: "2021-08-25T17:46:23Z"
          message: ReplicaSet "currency-exchange-86758cd5cb" has successfully progressed.
          reason: NewReplicaSetAvailable
          status: "True"
          type: Progressing
      observedGeneration: 1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
