version: "3.7"

services: 
    currency-exchange:
        image: ezazulhaq02/currency-exchnage-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports: 
            - 8001:8001
        networks: 
            - currency-network

networks: 
    currency-network: